Repository GregoryBevan/escape-camp, pull requests merged in 2023-06, with the labels that each got.

#26 ✨ Start the game when 4 teams are added
  .run/EscapeCampApplicationKt.run.xml
  backend/src/integrationTest/kotlin/me/elgregos/escapecamp/game/api/AddTeamApiStepDefinition.kt
  backend/src/integrationTest/kotlin/me/elgregos/escapecamp/game/api/CreateGameApiStepDefinition.kt
  backend/src/integrationTest/kotlin/me/elgregos/escapecamp/game/api/GameClient.kt
  backend/src/integrationTest/resources/features.game.api/02-add-team-api.feature
  backend/src/main/kotlin/me/elgregos/escapecamp/config/security/jwt/TokenProvider.kt
  backend/src/main/kotlin/me/elgregos/escapecamp/config/sse/ServerSentEventConfig.kt
  backend/src/main/kotlin/me/elgregos/escapecamp/config/sse/ServerSentEventService.kt
  backend/src/main/kotlin/me/elgregos/escapecamp/game/api/GameController.kt
  backend/src/main/kotlin/me/elgregos/escapecamp/game/api/dto/GameStreamEvent.kt
  backend/src/main/kotlin/me/elgregos/escapecamp/game/domain/entity/Game.kt
  backend/src/main/kotlin/me/elgregos/escapecamp/game/domain/event/GameAggregate.kt
  backend/src/main/kotlin/me/elgregos/escapecamp/game/domain/event/GameEvent.kt
  backend/src/main/kotlin/me/elgregos/escapecamp/game/infrastructure/event/GameServerSentEventSubscriber.kt
  backend/src/test/kotlin/me/elgregos/escapecamp/game/domain/event/GameAggregateTest.kt
  backend/src/test/kotlin/me/elgregos/escapecamp/game/domain/event/GameEvents.kt
Labels: enhancement

#32 👔 Assign first riddle to team according to registration order
  backend/src/integrationTest/kotlin/me/elgregos/escapecamp/features/SharedGivenStepDefinition.kt
  backend/src/integrationTest/kotlin/me/elgregos/escapecamp/features/SharedWhenStepDefinition.kt
  backend/src/integrationTest/kotlin/me/elgregos/escapecamp/game/api/AddTeamApiStepDefinition.kt
  backend/src/integrationTest/kotlin/me/elgregos/escapecamp/game/api/AssignNextTeamRiddleApiStepDefinition.kt
  backend/src/integrationTest/kotlin/me/elgregos/escapecamp/game/api/GameClient.kt
  backend/src/integrationTest/resources/features.game.api/02-add-team-api.feature
  backend/src/integrationTest/resources/features.game.api/03-assign-next-team-riddle-api.feature
  backend/src/main/kotlin/me/elgregos/escapecamp/config/exception/GameException.kt
  backend/src/main/kotlin/me/elgregos/escapecamp/game/api/GameController.kt
  backend/src/main/kotlin/me/elgregos/escapecamp/game/application/GameCommand.kt
  backend/src/main/kotlin/me/elgregos/escapecamp/game/application/GameCommandHandler.kt
  backend/src/main/kotlin/me/elgregos/escapecamp/game/application/RiddleService.kt
  backend/src/main/kotlin/me/elgregos/escapecamp/game/domain/entity/Game.kt
  backend/src/main/kotlin/me/elgregos/escapecamp/game/domain/entity/Riddle.kt
  backend/src/main/kotlin/me/elgregos/escapecamp/game/domain/entity/Team.kt
  backend/src/main/kotlin/me/elgregos/escapecamp/game/domain/event/GameAggregate.kt
  backend/src/main/kotlin/me/elgregos/escapecamp/game/domain/event/GameEvent.kt
  backend/src/main/kotlin/me/elgregos/escapecamp/game/infrastructure/event/GameServerSentEventSubscriber.kt
  backend/src/main/resources/riddles/riddle-1.md
  backend/src/main/resources/riddles/riddle-2.md
  backend/src/main/resources/riddles/riddle-3.md
  backend/src/main/resources/riddles/riddle-4.md
  backend/src/main/resources/riddles/story.md
  backend/src/test/kotlin/me/elgregos/escapecamp/game/application/RiddleServiceTest.kt
  backend/src/test/kotlin/me/elgregos/escapecamp/game/domain/entity/GameTest.kt
  backend/src/test/kotlin/me/elgregos/escapecamp/game/domain/entity/Games.kt
  backend/src/test/kotlin/me/elgregos/escapecamp/game/domain/entity/RiddleTest.kt
  backend/src/test/kotlin/me/elgregos/escapecamp/game/domain/entity/Riddles.kt
  backend/src/test/kotlin/me/elgregos/escapecamp/game/domain/entity/TeamTest.kt
  backend/src/test/kotlin/me/elgregos/escapecamp/game/domain/entity/Teams.kt
  backend/src/test/kotlin/me/elgregos/escapecamp/game/domain/event/GameAggregateAddTeamTest.kt
  backend/src/test/kotlin/me/elgregos/escapecamp/game/domain/event/GameAggregateAssignTeamNextRiddleTest.kt
  backend/src/test/kotlin/me/elgregos/escapecamp/game/domain/event/GameAggregateCreateGameTest.kt
  backend/src/test/kotlin/me/elgregos/escapecamp/game/domain/event/GameEventTest.kt
  backend/src/test/kotlin/me/elgregos/escapecamp/game/domain/event/GameEvents.kt
Labels: enhancement

#33 ✨ Check riddle solution endpoint
  .run/EscapeCampApplicationKt.run.xml
  backend/docker-compose.yml
  backend/src/integrationTest/kotlin/me/elgregos/escapecamp/features/SharedGivenStepDefinition.kt
  backend/src/integrationTest/kotlin/me/elgregos/escapecamp/game/api/AssignNextTeamRiddleApiStepDefinition.kt
  backend/src/integrationTest/kotlin/me/elgregos/escapecamp/game/api/CheckRiddleSolutionApiStepDefinition.kt
  backend/src/integrationTest/kotlin/me/elgregos/escapecamp/game/api/GameClient.kt
  backend/src/integrationTest/resources/features.game.api/03-assign-next-team-riddle-api.feature
  backend/src/integrationTest/resources/features.game.api/04-check-riddle-solution-api.feature
  backend/src/main/kotlin/me/elgregos/escapecamp/config/exception/GameException.kt
  backend/src/main/kotlin/me/elgregos/escapecamp/game/api/GameController.kt
  backend/src/main/kotlin/me/elgregos/escapecamp/game/api/dto/RiddleSolutionDTO.kt
  backend/src/main/kotlin/me/elgregos/escapecamp/game/application/GameCommand.kt
  backend/src/main/kotlin/me/elgregos/escapecamp/game/application/GameCommandHandler.kt
  backend/src/main/kotlin/me/elgregos/escapecamp/game/application/RiddleService.kt
  backend/src/main/kotlin/me/elgregos/escapecamp/game/domain/entity/Game.kt
  backend/src/main/kotlin/me/elgregos/escapecamp/game/domain/entity/Riddle.kt
  backend/src/main/kotlin/me/elgregos/escapecamp/game/domain/entity/Team.kt
  backend/src/main/kotlin/me/elgregos/escapecamp/game/domain/event/GameAggregate.kt
  backend/src/main/kotlin/me/elgregos/escapecamp/game/domain/event/GameEvent.kt
  backend/src/main/kotlin/me/elgregos/escapecamp/game/domain/event/GameEventRepository.kt
  backend/src/main/kotlin/me/elgregos/escapecamp/game/domain/service/RiddleSolutionChecker.kt
  backend/src/main/resources/application.yml
  backend/src/test/kotlin/me/elgregos/escapecamp/game/application/RiddleServiceTest.kt
  backend/src/test/kotlin/me/elgregos/escapecamp/game/domain/entity/GameTest.kt
  backend/src/test/kotlin/me/elgregos/escapecamp/game/domain/entity/Games.kt
  backend/src/test/kotlin/me/elgregos/escapecamp/game/domain/entity/RiddleTest.kt
  backend/src/test/kotlin/me/elgregos/escapecamp/game/domain/entity/Riddles.kt
  backend/src/test/kotlin/me/elgregos/escapecamp/game/domain/entity/TeamTest.kt
  backend/src/test/kotlin/me/elgregos/escapecamp/game/domain/entity/Teams.kt
  backend/src/test/kotlin/me/elgregos/escapecamp/game/domain/event/GameAggregateAddTeamTest.kt
  backend/src/test/kotlin/me/elgregos/escapecamp/game/domain/event/GameAggregateAssignTeamNextRiddleTest.kt
  backend/src/test/kotlin/me/elgregos/escapecamp/game/domain/event/GameAggregateCheckRiddleSolutionTest.kt
  backend/src/test/kotlin/me/elgregos/escapecamp/game/domain/event/GameAggregateCreateGameTest.kt
  backend/src/test/kotlin/me/elgregos/escapecamp/game/domain/event/GameEvents.kt
  backend/src/test/kotlin/me/elgregos/escapecamp/game/domain/service/MockedRiddleSolutionChecker.kt
Labels: enhancement

#37 👔 Assign next riddle after previous solved
  backend/src/main/kotlin/me/elgregos/escapecamp/game/domain/entity/Game.kt
  backend/src/main/kotlin/me/elgregos/escapecamp/game/domain/entity/Team.kt
  backend/src/main/kotlin/me/elgregos/escapecamp/game/domain/event/GameAggregate.kt
  backend/src/test/kotlin/me/elgregos/escapecamp/game/domain/entity/GameTest.kt
  backend/src/test/kotlin/me/elgregos/escapecamp/game/domain/entity/Games.kt
  backend/src/test/kotlin/me/elgregos/escapecamp/game/domain/entity/Riddles.kt
  backend/src/test/kotlin/me/elgregos/escapecamp/game/domain/entity/TeamTest.kt
  backend/src/test/kotlin/me/elgregos/escapecamp/game/domain/entity/Teams.kt
  backend/src/test/kotlin/me/elgregos/escapecamp/game/domain/event/GameAggregateAssignTeamNextRiddleTest.kt
  backend/src/test/kotlin/me/elgregos/escapecamp/game/domain/event/GameAggregateCheckRiddleSolutionTest.kt
  backend/src/test/kotlin/me/elgregos/escapecamp/game/domain/event/GameEvents.kt
Labels: enhancement

#39 🐛 Avoid index out of bound on riddle assignment
  backend/src/main/kotlin/me/elgregos/escapecamp/game/domain/entity/Game.kt
  backend/src/test/kotlin/me/elgregos/escapecamp/game/domain/entity/GameTest.kt
  backend/src/test/kotlin/me/elgregos/escapecamp/game/domain/entity/Games.kt
  backend/src/test/kotlin/me/elgregos/escapecamp/game/domain/entity/Riddles.kt
  backend/src/test/kotlin/me/elgregos/escapecamp/game/domain/entity/Teams.kt
Labels: bug

#40 ✨ Endpoints to list all games and find game by Id
  backend/build.gradle.kts
  backend/src/integrationTest/kotlin/me/elgregos/escapecamp/game/api/GameClient.kt
  backend/src/integrationTest/kotlin/me/elgregos/escapecamp/game/api/ListGameApiStepDefinition.kt
  backend/src/integrationTest/resources/features.game.api/05-list-games-api.feature
  backend/src/main/kotlin/me/elgregos/escapecamp/game/api/GameController.kt
  backend/src/main/kotlin/me/elgregos/escapecamp/game/application/GameCommandHandler.kt
  backend/src/main/kotlin/me/elgregos/escapecamp/game/application/GameService.kt
  backend/src/main/kotlin/me/elgregos/escapecamp/game/application/RiddleService.kt
  backend/src/main/kotlin/me/elgregos/escapecamp/game/domain/entity/Game.kt
  backend/src/main/kotlin/me/elgregos/escapecamp/game/domain/repository/GameRepository.kt
  backend/src/main/kotlin/me/elgregos/escapecamp/game/infrastructure/projection/GameEntity.kt
  backend/src/main/kotlin/me/elgregos/escapecamp/game/infrastructure/projection/GameProjectionRepository.kt
  backend/src/main/kotlin/me/elgregos/escapecamp/game/infrastructure/projection/GameProjectionSubscriber.kt
  backend/src/main/resources/db/changelog/db-changelog.sql
  backend/src/test/kotlin/me/elgregos/escapecamp/game/application/GameServiceTest.kt
  backend/src/test/kotlin/me/elgregos/escapecamp/game/domain/entity/Games.kt
  backend/src/test/kotlin/me/elgregos/escapecamp/game/domain/entity/Riddles.kt
  backend/src/test/kotlin/me/elgregos/escapecamp/game/domain/event/GameAggregateCreateGameTest.kt
  backend/src/test/kotlin/me/elgregos/escapecamp/game/domain/event/GameEvents.kt
  backend/src/test/kotlin/me/elgregos/escapecamp/game/infrastructure/projection/GameEntities.kt
  backend/src/test/kotlin/me/elgregos/escapecamp/game/infrastructure/projection/GameEntityTest.kt
Labels: enhancement

#44 ✨ Detect end of game when all riddle solved by a team
  backend/src/integrationTest/kotlin/me/elgregos/escapecamp/features/SharedGivenStepDefinition.kt
  backend/src/integrationTest/kotlin/me/elgregos/escapecamp/features/SharedThenStepDefinition.kt
  backend/src/integrationTest/kotlin/me/elgregos/escapecamp/game/api/AddTeamApiStepDefinition.kt
  backend/src/integrationTest/kotlin/me/elgregos/escapecamp/game/api/CheckRiddleSolutionApiStepDefinition.kt
  backend/src/integrationTest/kotlin/me/elgregos/escapecamp/game/api/ListGameApiStepDefinition.kt
  backend/src/integrationTest/resources/features.game.api/04-check-riddle-solution-api.feature
  backend/src/main/kotlin/me/elgregos/escapecamp/EscapeCampApplication.kt
  backend/src/main/kotlin/me/elgregos/escapecamp/config/exception/GameException.kt
  backend/src/main/kotlin/me/elgregos/escapecamp/config/game/GameConfig.kt
  backend/src/main/kotlin/me/elgregos/escapecamp/game/application/GameCommandHandler.kt
  backend/src/main/kotlin/me/elgregos/escapecamp/game/application/GameService.kt
  backend/src/main/kotlin/me/elgregos/escapecamp/game/domain/entity/Game.kt
  backend/src/main/kotlin/me/elgregos/escapecamp/game/domain/entity/Riddle.kt
  backend/src/main/kotlin/me/elgregos/escapecamp/game/domain/entity/Team.kt
  backend/src/main/kotlin/me/elgregos/escapecamp/game/domain/event/GameAggregate.kt
  backend/src/main/kotlin/me/elgregos/escapecamp/game/domain/event/GameEvent.kt
  backend/src/main/kotlin/me/elgregos/escapecamp/game/domain/service/RiddleSolutionChecker.kt
  backend/src/main/kotlin/me/elgregos/escapecamp/game/infrastructure/projection/GameEntity.kt
  backend/src/main/resources/application.yml
  backend/src/test/kotlin/me/elgregos/escapecamp/game/application/GameServiceTest.kt
  backend/src/test/kotlin/me/elgregos/escapecamp/game/domain/entity/GameTest.kt
  backend/src/test/kotlin/me/elgregos/escapecamp/game/domain/entity/Games.kt
  backend/src/test/kotlin/me/elgregos/escapecamp/game/domain/entity/Riddles.kt
  backend/src/test/kotlin/me/elgregos/escapecamp/game/domain/entity/TeamTest.kt
  backend/src/test/kotlin/me/elgregos/escapecamp/game/domain/entity/Teams.kt
  backend/src/test/kotlin/me/elgregos/escapecamp/game/domain/event/GameAggregateAddTeamTest.kt
  backend/src/test/kotlin/me/elgregos/escapecamp/game/domain/event/GameAggregateAssignTeamNextRiddleTest.kt
  backend/src/test/kotlin/me/elgregos/escapecamp/game/domain/event/GameAggregateCheckRiddleSolutionTest.kt
  backend/src/test/kotlin/me/elgregos/escapecamp/game/domain/event/GameAggregateCreateGameTest.kt
  backend/src/test/kotlin/me/elgregos/escapecamp/game/domain/event/GameEvents.kt
  backend/src/test/kotlin/me/elgregos/escapecamp/game/domain/service/MockedRiddleSolutionChecker.kt
Labels: enhancement

#56 ✨ app notifications
  frontend/src/ec-controller.ts
  frontend/src/ec.css
  frontend/src/styles.ts
Labels: enhancement

#58 ✨ Trigger server sent event heartbeat on game created event
  backend/src/main/kotlin/me/elgregos/escapecamp/config/sse/ServerSentEventService.kt
  backend/src/main/kotlin/me/elgregos/escapecamp/game/infrastructure/event/GameServerSentEventSubscriber.kt
  backend/src/main/resources/application.yml
Labels: enhancement

#61 🚸 Ignore case while checking solution
  backend/src/main/kotlin/me/elgregos/escapecamp/game/domain/service/RiddleSolutionChecker.kt
  backend/src/test/kotlin/me/elgregos/escapecamp/game/application/GameServiceTest.kt
Labels: enhancement

#62 🚸 Enable chrome notifications on mobile
  backend/build.gradle.kts
  backend/src/main/kotlin/me/elgregos/escapecamp/config/security/SecurityConfig.kt
  frontend/index.html
  frontend/sw.js
Labels: frontend
